# .github/workflows/build-exe.yml
name: Build EXE and Upload to Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kodu klonla
      uses: actions/checkout@v2

    - name: Python 3.12 kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Gerekenleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: EXE dosyasını oluştur
      run: pyinstaller --onefile main.py

    - name: EXE dosyasını GitHub Release'e yükle
      uses: softprops/action-gh-release@v1
      with:
        files: dist/your_script.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
